import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:screenshot/screenshot.dart';
import '../models/receipt_result.dart';

class ReceiptGenerator {
  static Future<Uint8List?> generate(
    ReceiptResult result,
    BuildContext context,
  ) async {
    final controller = ScreenshotController();
    return controller.captureFromWidget(
      InheritedTheme.captureAll(
        context,
        MediaQuery(
          data: MediaQuery.of(context),
          child: _ReceiptWidget(result: result),
        ),
      ),
      pixelRatio: 2.0,
    );
  }
}

class _ReceiptWidget extends StatelessWidget {
  final ReceiptResult result;
  const _ReceiptWidget({required this.result});

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.white,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 32),
        child: SizedBox(
          width: 320,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              // Header
              const Text(
                'SPLITAA',
                style: TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 5,
                  color: Colors.black,
                ),
              ),
              const SizedBox(height: 4),
              Text(
                _fmtDate(result.timestamp),
                style: const TextStyle(fontSize: 11, color: Colors.grey),
              ),
              const SizedBox(height: 16),
              const Divider(color: Colors.black),
              const SizedBox(height: 8),

              // Items
              ...result.items.map(
                (item) => Padding(
                  padding: const EdgeInsets.symmetric(vertical: 3),
                  child: Row(
                    children: [
                      Expanded(
                        child: Text(item.name,
                            style: const TextStyle(fontSize: 13, color: Colors.black)),
                      ),
                      Text(
                        'RM ${item.price.toStringAsFixed(2)}',
                        style: const TextStyle(fontSize: 13, color: Colors.black),
                      ),
                    ],
                  ),
                ),
              ),

              const SizedBox(height: 8),
              const Divider(color: Colors.grey),

              // Subtotal
              _row('Subtotal', result.subtotal, grey: true),

              // Fees
              ...result.fees.map((fee) {
                final amount = fee.compute(result.subtotal);
                final label =
                    '${fee.label} (${fee.isPercentage ? '${fee.value}%' : 'RM ${fee.value.toStringAsFixed(2)}'})';
                return _row(label, amount, grey: true, isDiscount: fee.isDiscount);
              }),

              const Divider(color: Colors.black),

              // Total
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 4),
                child: Row(
                  children: [
                    const Expanded(
                      child: Text(
                        'TOTAL',
                        style: TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 16,
                            color: Colors.black),
                      ),
                    ),
                    Text(
                      'RM ${result.total.toStringAsFixed(2)}',
                      style: const TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 24),

              // QR placeholder
              Container(
                width: 80,
                height: 80,
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.grey),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: const Center(
                  child: Text('QR\nComing\nSoon',
                      textAlign: TextAlign.center,
                      style: TextStyle(fontSize: 10, color: Colors.grey)),
                ),
              ),
              const SizedBox(height: 6),
              const Text('Scan to pay', style: TextStyle(fontSize: 10, color: Colors.grey)),

              const SizedBox(height: 20),
              const Text(
                '— Generated by Splitaa —',
                style: TextStyle(fontSize: 10, color: Colors.grey),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _row(String label, double amount,
      {bool grey = false, bool isDiscount = false}) {
    final color = isDiscount ? Colors.green.shade700 : (grey ? Colors.grey.shade600 : Colors.black);
    final sign = isDiscount ? '-' : (amount < 0 ? '-' : '');
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(
        children: [
          Expanded(child: Text(label, style: TextStyle(fontSize: 12, color: color))),
          Text(
            '$sign RM ${amount.abs().toStringAsFixed(2)}',
            style: TextStyle(fontSize: 12, color: color),
          ),
        ],
      ),
    );
  }

  String _fmtDate(DateTime dt) =>
      '${dt.day.toString().padLeft(2, '0')}/${dt.month.toString().padLeft(2, '0')}/${dt.year}  '
      '${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}';
}
